Feat: Adding the Database init with EF-Core
activecourses/StudyCircle pull request #2
Opened 2024-10-05 18:05 UTC by ziad-ashraf7

- Added the Database Models: User , Club and ClubMember.
- Added the Models Configuration files: UserConfig, ClubConfig and ClubMemberConfig.
- Added the AppDbContext and Connection String for the Database.

2024-10-05 18:10 UTC, amrmostafa800 commented on backend/Database/Database.cs
DatabaseConfig Method Is Unused

2024-10-05 21:49 UTC, NulMo requested changes

2024-10-05 21:49 UTC, NulMo commented on backend/API/appsettings.json
> +  "constr": "Server=.; Database = StudyCircle; Integrated Security = SSPI; TrustServerCertificate = True;",
Change "constr" to "ConnectionString" for better naming description.

2024-10-05 21:49 UTC, NulMo commented on backend/Database/Models/User.cs
> +    public int id { get; set; }
Change id to Id

2024-10-05 21:49 UTC, NulMo commented on backend/Database/Models/Club.cs
> +    public int id { get; set; }
Change id to Id for better naming conventions.

2024-10-05 21:49 UTC, NulMo commented on backend/Database/AppDbContext.cs
> +        var connectionString = conf.GetSection("constr").Value;
Change "constr" here to ConnectionString also.

2024-10-06 14:03 UTC, amrmostafa800 approved these changes

2024-10-06 14:03 UTC, MuhammadSaadd commented on backend/API/appsettings.json
> +  "ConnectionString": "Server=.; Database = StudyCircle; Integrated Security = SSPI; TrustServerCertificate = True;",
usually ConnectionString key added inside DefaultConnectios key

2024-10-06 14:03 UTC, MuhammadSaadd commented on backend/Database/AppDbContext.cs
> +    public AppDbContext()
why are you using empty constructor?

2024-10-06 14:03 UTC, MuhammadSaadd commented on backend/Database/AppDbContext.cs
> +        var connectionString = conf.GetSection("ConnectionString").Value;
you can use program file to add connection string using builder approach

2024-10-06 14:03 UTC, MuhammadSaadd commented on backend/Database/AppDbContext.cs
> +        new UserConfig().Configure(modelBuilder.Entity<User>());
i think that you can apply configs in another general way

2024-10-06 14:03 UTC, MuhammadSaadd commented on backend/Database/Models/Club.cs
> +    public ICollection<ClubMember> ClubMembers { get; set; } = new List<ClubMember>();
do you think virtual keyword is missing here?

2024-10-06 14:03 UTC, MuhammadSaadd commented on backend/Database/Models/ClubMember.cs
> +    public required User User { get; set; }
public User User { get; set; } = null!;
'null!' is better than required here, because required properties need to be assigned immediately while initialization

2024-10-06 14:10 UTC, MuhammadSaadd commented on backend/Database/AppDbContext.cs
> +        var connectionString = conf.GetSection("ConnectionString").Value;
![Uploading image.png…]()

2024-10-06 14:10 UTC, MuhammadSaadd commented on backend/Database/AppDbContext.cs
> +        var connectionString = conf.GetSection("ConnectionString").Value;
![image](https://github.com/user-attachments/assets/852d9ade-23f2-4b81-8ead-c716fd219624)

2024-10-06 15:15 UTC, amrmostafa800 approved these changes

2024-10-07 13:15 UTC, merged